### ISSUE TITLE
fastmod: kind of similar to `sad`

### ISSUE THREAD

**Issue by ghuls** [TaKO8Ki/awesome-alternatives-in-rust#23]
https://github.com/facebookincubator/fastmod

fastmod is a fast partial replacement for codemod. Like codemod, it is a tool to assist you with large-scale codebase refactors, and it supports most of codemod's options. fastmod's major philosophical difference from codemod is that it is focused on improving the use case "I want to use interactive mode to make sure my regex is correct, and then I want to apply the regex everywhere". For this use case, it offers much better performance than codemod. Accordingly, fastmod does not support codemod's --start, --end, or --count options, nor does it support anything like codemod's Python API.

**Comment by TaKO8Ki** [comment]
@ghuls Thank you for the information!
