### ISSUE TITLE
Sort-of rewrites?

### ISSUE THREAD

**Issue by casey** [TaKO8Ki/awesome-alternatives-in-rust#28]
I wrote a utility called [just](https://github.com/casey/just) that is a replacement for using make as a command runner. However, it’s not a build system, so it’s not a full replacement for make. I wanted to open a PR adding it, but wasn’t sure it would be a good fit.

What’s the policy for sort-of replacements for existing utilities?

**Comment by TaKO8Ki** [comment]
@casey

If the author, that is you in this case isn't negative about adding your software to this repository, sort-of replacements are also welcome!

**Comment by casey** [comment]
Awesome! I opened #32. Thanks for maintaining this repo!
