### ISSUE TITLE
[For all contributors] Do you think I should change the repository name?

### ISSUE THREAD

**Issue by TaKO8Ki** [TaKO8Ki/awesome-alternatives-in-rust#29]
Some people in reddit suggest renaming to the repository name. Do you think I should change the repository name? If so, please give me your idea for this repository's name.

I'm wondering whether I should do it.

ref:

> Just a heads up that I got a lot random whining from folks about calling ripgrep a "replacement" for grep so long as it wasn't POSIX compatible or otherwise bug-for-bug compatible with grep. In response to that, I added a FAQ item: https://github.com/BurntSushi/ripgrep/blob/master/FAQ.md#posix4ever
>
> And I'm not really a fan of calling this "Awesome Rewrite it in Rust." I didn't set out to "rewrite grep in Rust." Not only was it not my intent, but ripgrep is quite literally not a rewrite of grep in Rust in any sense of the word.

https://www.reddit.com/r/rust/comments/nm96n1/awesome_rewrite_it_in_rust_a_curated_list_of/gzold43?utm_source=share&utm_medium=web2x&context=3

> May I suggest a rename to "Alternatives in Rust (AIR)"?

https://www.reddit.com/r/rust/comments/nm96n1/awesome_rewrite_it_in_rust_a_curated_list_of/gzny13l?utm_source=share&utm_medium=web2x&context=3

> I think having a list like this is awesome, just change the name might be good.

https://www.reddit.com/r/rust/comments/nm96n1/awesome_rewrite_it_in_rust_a_curated_list_of/gzpvc8q?utm_source=share&utm_medium=web2x&context=3

> "Awesome Alternatives" might be better?

https://www.reddit.com/r/rust/comments/nm96n1/awesome_rewrite_it_in_rust_a_curated_list_of/gzoybro?utm_source=share&utm_medium=web2x&context=3

> My bikeshed for the rename is "Awesome Rust Rewrites"

https://www.reddit.com/r/rust/comments/nm96n1/awesome_rewrite_it_in_rust_a_curated_list_of/gzoej3v?utm_source=share&utm_medium=web2x&context=3

**Comment by kartva** [comment]
> Awesome Rust Rewrites

Sounds more accurate.

**Comment by ssokolow** [comment]
I think "rewrites" is the problematic word, because it implies preserving the semantics of the *implementation* too strongly.

Something like "alternatives" would be more in line with "aims to serve the same purpose with a possibly very different design".

**Comment by shenlebantongying** [comment]
I dislike "rewrites" too because it implies better like "refactor".

Some of them indeed better than original, but some rust version is just crap wich much fewer features.

It also implies the old ones are going to be replaced,  but NO, the original ones are still evolving and being used everywhere.

AFAIK, only the Coreutils can be considered as a "rewrite" as it has a complete test suite to make sure compatibility compliance.

**Comment by PoignardAzur** [comment]
I recommend **Awesome Alternatives in Rust**.

**Comment by TaKO8Ki** [comment]
Thank you for your advices! I'm going to rename the repository name to "Awesome Alternatives in Rust" (awesome-alternatives-in-rust)
