### ISSUE TITLE
delta as a replacement for diff-highlight and diff-so-fancy

### ISSUE THREAD

**Issue by ssokolow** [TaKO8Ki/awesome-alternatives-in-rust#54]
I haven't checked how complete they are, but [delta](https://github.com/dandavison/delta) is a Rust-based diff viewer that lists "`diff-highlight` and `diff-so-fancy` emulation modes" as one of its features and [sad](https://github.com/ms-jpq/sad) says "Any git compatible colourizer would work. I perfer these two:" before listing delta and diff-so-fancy.

**Comment by slaughtering** [comment]
Now solved by https://github.com/TaKO8Ki/awesome-alternatives-in-rust/pull/45
